Repository Kernel360/f1-KernelSquare-backend, pull requests merged in 2023-12, with the labels that each got.

#1 [feat] entity 초기 세팅
  build.gradle
  src/main/java/com/kernel360/kernelsquare/KernelSquareApplication.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/entity/Answer.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/TokenDto.java
  src/main/java/com/kernel360/kernelsquare/domain/authority/entity/Authority.java
  src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
  src/main/java/com/kernel360/kernelsquare/domain/member/controller/MemberController.java
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/FindMemberResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
  src/main/java/com/kernel360/kernelsquare/domain/member/repository/MemberRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/entity/MemberAnswerVote.java
  src/main/java/com/kernel360/kernelsquare/domain/member_authority/entity/MemberAuthority.java
  src/main/java/com/kernel360/kernelsquare/domain/member_tech_stack/entity/MemberTechStack.java
  src/main/java/com/kernel360/kernelsquare/domain/question/entity/Question.java
  src/main/java/com/kernel360/kernelsquare/domain/question_tech_stack/entity/QuestionTechStack.java
  src/main/java/com/kernel360/kernelsquare/domain/rank/entity/Rank.java
  src/main/java/com/kernel360/kernelsquare/domain/social_login/entity/SocialLogin.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/entity/TechStack.java
  src/main/java/com/kernel360/kernelsquare/global/config/CorsConfig.java
  src/main/java/com/kernel360/kernelsquare/global/config/JpaAuditingConfig.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/java/com/kernel360/kernelsquare/global/domain/AnswerRankType.java
  src/main/java/com/kernel360/kernelsquare/global/domain/AuthorityType.java
  src/main/java/com/kernel360/kernelsquare/global/domain/SocialProvider.java
  src/main/java/com/kernel360/kernelsquare/global/dto/CommonApiResponse.java
  src/main/java/com/kernel360/kernelsquare/global/entity/BaseEntity.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/JwtFilter.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/TokenProvider.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/kernel360/kernelsquare/KernelSquareApplicationTests.java
Labels: Feature, Setting

#4 [setting] 배포 환경 세팅
  .github/workflows/gradle.yml
  appspec.yml
  scripts/deploy.sh
Labels: Setting, Deploy

#7 [setting] 자동 배포 -> 수동 배포 환경 세팅
  .github/workflows/gradle.yml
Labels: Setting, Deploy, Chore

#8 [refactor] MemberController 및 공통 응답 양식 수정, MemberController 및 MemberService 테스트 추가
  .github/ISSUE_TEMPLATE/feedback-form.yml
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
  src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
  src/main/java/com/kernel360/kernelsquare/domain/member/controller/MemberController.java
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/FindMemberResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
  src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/ApiResponse.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/StatusCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/GlobalExceptionHandler.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/AuthErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/ErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/MemberErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/dto/ErrorResponse.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/exception/BusinessException.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/MemberResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/ResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/domain/AuthorityType.java
  src/main/java/com/kernel360/kernelsquare/global/dto/.gitkeep
  src/main/java/com/kernel360/kernelsquare/global/dto/CommonApiResponse.java
  src/test/java/com/kernel360/kernelsquare/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java
Labels: Feature, Test, Refactor

#9 [refactor] controller 수정 및 커스텀 코드를 위한 ServiceStatus 및 모든 RepsonseEntity 생성 통일을 위한 ResponseEntityFactory 생성
  src/main/java/com/kernel360/kernelsquare/domain/member/controller/MemberController.java
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/ApiResponse.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/ResponseEntityFactory.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/StatusCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/GlobalExceptionHandler.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/AuthErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/MemberErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/dto/ErrorResponse.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/MemberResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/MemberServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/ServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/TokenProvider.java
  src/main/resources/application.yml
  src/test/java/com/kernel360/kernelsquare/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java
Labels: Refactor

#10 [feat] 질문 기능 개발
  build.gradle
  src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
  src/main/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
  src/main/java/com/kernel360/kernelsquare/domain/question/controller/QuestionController.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/FindQuestionResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/UpdateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/question/entity/Question.java
  src/main/java/com/kernel360/kernelsquare/domain/question/repository/QuestionRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/question/service/QuestionService.java
  src/main/java/com/kernel360/kernelsquare/domain/question_tech_stack/entity/QuestionTechStack.java
  src/main/java/com/kernel360/kernelsquare/domain/question_tech_stack/repository/QuestionTechStackRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/rank/entity/Rank.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/entity/TechStack.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/repository/TechStackRepository.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/GlobalExceptionHandler.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/QuestionErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/QuestionResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/QuestionServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/dto/PageResponse.java
  src/main/java/com/kernel360/kernelsquare/global/dto/Pagination.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/kernel360/kernelsquare/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question/controller/QuestionControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
  src/test/resources/application.yml
Labels: Feature, Setting, API, Test, Refactor

#17 [feat] 단일 질문에 대한 복수 답변 조회 기능
  src/main/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerController.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/FindAnswerResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/entity/Answer.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/repository/AnswerRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/AnswerResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/QuestionResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AnswerServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java
Labels: Feature, API

#22 [feat] 로그 AOP 1차 완성
  build.gradle
  src/main/java/com/kernel360/kernelsquare/global/aop/Logging.java
  src/main/resources/logback.xml
Labels: Feature

#27 [feat] 답변 생성 기능 & 기타 변경사항
  src/main/java/com/kernel360/kernelsquare/KernelSquareApplication.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerController.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/CreateAnswerRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/FindAnswerResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
  src/main/java/com/kernel360/kernelsquare/global/aop/Logging.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/AnswerResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/QuestionResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AnswerServiceStatus.java
  src/main/resources/data.sql
  src/test/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java
Labels: Feature, API, Test, Refactor

#29 [feat] 기술 스택 생성 기능 개발
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackController.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/CreateTechStackRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/CreateTechStackResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/entity/TechStack.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/TechStackErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/TechStackResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TechStackServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java
Labels: Feature

#30 [feat] 답변 수정 & 삭제
  src/main/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerController.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/UpdateAnswerRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/entity/Answer.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/AnswerErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AnswerServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java
Labels: Feature, API, Test
