Repository Kernel360/f1-KernelSquare-backend, pull requests merged in 2024-01, with the labels that each got.

#37 [feat] 등급 생성
  src/main/java/com/kernel360/kernelsquare/domain/level/controller/LevelController.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/repository/TechStackRepository.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/LevelErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/LevelResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/LevelServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java
Labels: Feature, API, Test

#38 [env]CODEOWNERS 파일 추가
  .github/CODEOWNERS
Labels: Setting

#39 등급 생성 응답코드 수정
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/LevelServiceStatus.java
Labels: Chore

#36 [feat] 기술 스택 모든 조회 기능 개발
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackController.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/CreateTechStackResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/FindAllTechStacksResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/entity/TechStack.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/TechStackResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TechStackServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/repository/TechStackRepositoryTest.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java
Labels: Feature, API, Test

#41 [feat] 기술 스택 삭제 기능 개발
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackController.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/FindAllTechStacksResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/TechStackResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TechStackServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java
Labels: Feature, API, Test, Refactor

#42 [feat] 기술 스택 수정 기능 개발
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackController.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/UpdateTechStackRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/entity/TechStack.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/TechStackResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TechStackServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackServiceTest.java
Labels: Feature, API, Test, Refactor

#44 [feat] 등급 조회 기능
  src/main/java/com/kernel360/kernelsquare/domain/level/controller/LevelController.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/FindAllLevelResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/LevelDto.java
  src/main/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/LevelResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/LevelServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java
Labels: Feature, API, Test

#53 [refactor] 기술 스택 수정 서비스 로직에 예외 처리 로직 추가
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/repository/TechStackRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/service/TechStackService.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/repository/TechStackRepositoryTest.java
Labels: Test, Refactor

#55 [refactor] 질문 관련 코드들 리팩토링
  src/main/java/com/kernel360/kernelsquare/domain/answer/entity/Answer.java
  src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
  src/main/java/com/kernel360/kernelsquare/domain/question/controller/QuestionController.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/FindQuestionResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/question/entity/Question.java
  src/main/java/com/kernel360/kernelsquare/domain/question/service/QuestionService.java
  src/main/java/com/kernel360/kernelsquare/global/dto/Pagination.java
  src/test/java/com/kernel360/kernelsquare/domain/question/controller/QuestionControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question_tech_stack/repository/QuestionTechStackRepositoryTest.java
Labels: Refactor

#56 [feat] 투표 생성 및 삭제 기능
  src/main/java/com/kernel360/kernelsquare/domain/answer/repository/AnswerRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/controller/MemberAnswerVoteController.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/dto/CreateMemberAnswerVoteRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/entity/MemberAnswerVote.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/repository/MemberAnswerVoteRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/service/MemberAnswerVoteService.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/MemberAnswerVoteErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/AnswerResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/MemberAnswerVoteResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AnswerServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/MemberAnswerVoteStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member_answer_vote/controller/MemberAnswerVoteControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member_answer_vote/repository/MemberAnswerVoteRepositoryTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member_answer_vote/service/MemberAnswerVoteServiceTest.java
Labels: Feature, API, Test

#58 [feat] 레벨 삭제 기능
  src/main/java/com/kernel360/kernelsquare/domain/level/controller/LevelController.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/DeleteLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
  src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/LevelResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/LevelServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java
Labels: Feature, API, Test

#61 [feat] 등급 수정 기능
  src/main/java/com/kernel360/kernelsquare/domain/level/controller/LevelController.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
  src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/GlobalExceptionHandler.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/CommonErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/LevelResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CommonServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/LevelServiceStatus.java
  src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java
Labels: Feature, API, Test

#69 [refactor] security API Endpoint / CORS 수정 / Valid annotation 예외 처리 추가
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/CreateAnswerRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/UpdateAnswerRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/controller/AuthController.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateEmailRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateNicknameRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/dto/CreateMemberAnswerVoteRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/UpdateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackController.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/CreateTechStackRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/UpdateTechStackRequest.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/ApiResponse.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/ResponseEntityFactory.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/GlobalExceptionHandler.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/TokenErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AuthorityServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CommonServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TokenServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/CorsConfig.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/java/com/kernel360/kernelsquare/global/constants/FilterHttpMethodConstants.java
  src/main/java/com/kernel360/kernelsquare/global/filter/JWTTokenSettingFilter.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/TokenProvider.java
  src/main/java/com/kernel360/kernelsquare/global/util/ExceptionMessageConverter.java
  src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
Labels: Setting, Deploy, Refactor, Chore

#66 [feat] 이미지 관련 기능 개발 1차 완료
  build.gradle
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/CreateAnswerRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/FindAnswerResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
  src/main/java/com/kernel360/kernelsquare/domain/image/component/ImageComponent.java
  src/main/java/com/kernel360/kernelsquare/domain/image/controller/ImageController.java
  src/main/java/com/kernel360/kernelsquare/domain/image/dto/CategoryDto.java
  src/main/java/com/kernel360/kernelsquare/domain/image/dto/UploadImageResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/image/service/ImageService.java
  src/main/java/com/kernel360/kernelsquare/domain/image/utils/ImageUtils.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/LevelDto.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/FindQuestionResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/UpdateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/question/service/QuestionService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/CategoryErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/ImageErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/ImageResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CategoryServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/ImageServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/S3Config.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/kernel360/kernelsquare/domain/image/controller/ImageControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/image/service/ImageServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepositoryTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question/controller/QuestionControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/controller/TechStackControllerTest.java
Labels: Feature, API, Test

#71 refactor : 질문 조회시 회원 아이디 응답에 포함하도록 수정
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/FindQuestionResponse.java
Labels: API, Refactor

#73 refactor : logout 시 api 호출 정상적으로 동작하지 않던 이슈 수정 및 JWTCheckFilter 추가
  src/main/java/com/kernel360/kernelsquare/global/common_response/ResponseEntityFactory.java
  src/main/java/com/kernel360/kernelsquare/global/config/CorsConfig.java
  src/main/java/com/kernel360/kernelsquare/global/config/RedisConfig.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/java/com/kernel360/kernelsquare/global/dto/.gitkeep
  src/main/java/com/kernel360/kernelsquare/global/filter/JWTSettingFilter.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/JWTAccessDeniedHandler.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/JWTAuthenticationEntryPoint.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/TokenProvider.java
  src/main/java/com/kernel360/kernelsquare/global/util/ExceptionMessageConverter.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: BugFix, API

#80 [bugfix] 이미지 URL 응답을 s3 주소가 빠진 상태로 보내는 문제
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/FindMemberResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/FindQuestionResponse.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/resources/data.sql
  src/test/java/com/kernel360/kernelsquare/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
Labels: BugFix

#81 [setting] 모니터링 환경 세팅
  build.gradle
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: Setting, Infra

#83 [refactor] AOP 리팩터링 1차
  src/main/java/com/kernel360/kernelsquare/global/aop/Logging.java
  src/main/java/com/kernel360/kernelsquare/global/aop/MDCFilter.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: Refactor

#98 [refactor] Level 로직 리팩토링
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/LevelDto.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/level/entity/Level.java
  src/main/java/com/kernel360/kernelsquare/domain/level/service/LevelService.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/UpdateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/resources/data.sql
  src/test/java/com/kernel360/kernelsquare/domain/level/controller/LevelControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java
Labels: Refactor

#92 [feat] 질문 리스트 검색 기능 구현
  build.gradle
  src/main/java/com/kernel360/kernelsquare/domain/search/controller/SearchController.java
  src/main/java/com/kernel360/kernelsquare/domain/search/repository/SearchRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/search/repository/SearchRepositoryImpl.java
  src/main/java/com/kernel360/kernelsquare/domain/search/service/SearchService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/QuestionResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/SearchResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/SearchServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/QueryDslConfig.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/resources/data.sql
  src/test/java/com/kernel360/kernelsquare/domain/search/controller/SearchControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/search/repository/SearchRepositoryTest.java
  src/test/java/com/kernel360/kernelsquare/domain/search/service/SearchServiceTest.java
Labels: Feature, API, Test

#102 [refactor] AuthController 내부 서비스 분리 및 인증 관련 테스트 작성, Auth 관련 클래스 리팩토링
  .github/workflows/gradle.yml
  src/main/java/com/kernel360/kernelsquare/domain/auth/controller/AuthController.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateEmailRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateNicknameRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/LoginRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/LoginResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/SignUpRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/TokenRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/TokenResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/service/AuthService.java
  src/main/java/com/kernel360/kernelsquare/domain/authority/entity/Authority.java
  src/main/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepository.java
  src/main/java/com/kernel360/kernelsquare/global/jwt/TokenProvider.java
  src/test/java/com/kernel360/kernelsquare/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/auth/service/AuthServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/auth/service/MemberDetailServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/repository/LevelRepositoryTest.java
  src/test/java/com/kernel360/kernelsquare/global/jwt/TokenProviderTest.java
  src/test/resources/application.yml
Labels: API, Test, Refactor

#104 [feat] 답변 전체 조회시 작성자 레벨과 조회자 투표 여부 추가
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/FindAnswerResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/entity/MemberAnswerVote.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/repository/MemberAnswerVoteRepository.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java
Labels: Feature, API, Test

#105 [setting] flyway 적용
  build.gradle
  src/main/resources/application.yml
  src/main/resources/db/migration/V1.0__init_table.sql
  src/main/resources/db/migration/V1.1__add_initial_data.sql
  src/test/resources/application.yml
Labels: Setting

#107 [bugfix] 답변 조회에서 이미지 절대URL로 보내게 FindAnswerResponse 수정
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/FindAnswerResponse.java
Labels: BugFix

#109 [bugfix] 로그인 응답 ROLE 정상적으로 보내주도록 LoginResponse 수정
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/LoginResponse.java
Labels: BugFix

#111 [test] 유효성 검증 테스트 추가
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/CreateAnswerRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/UpdateAnswerRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateEmailRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/CheckDuplicateNicknameRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/LoginRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/dto/SignUpRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/image/dto/ImageCategory.java
  src/main/java/com/kernel360/kernelsquare/domain/image/service/ImageService.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/CreateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/DeleteLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/level/dto/UpdateLevelRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/member_answer_vote/dto/CreateMemberAnswerVoteRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/CreateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/question/dto/UpdateQuestionRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/CreateReservationArticleRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/CreateTechStackRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/tech_stack/dto/UpdateTechStackRequest.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/dto/AnswerRequestDtoTest.java
  src/test/java/com/kernel360/kernelsquare/domain/auth/dto/AuthRequestDtoTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/dto/LevelRequestDtoTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member_answer_vote/dto/MemberAnswerVoteRequestDtoTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question/dto/QuestionRequestDtoTest.java
  src/test/java/com/kernel360/kernelsquare/domain/reservation_article/dto/ReservationArticleRequestDtoTest.java
  src/test/java/com/kernel360/kernelsquare/domain/tech_stack/dto/TechStackRequestDtoTest.java
Labels: Test, Refactor

#120 [feat] 채팅방 생성 기능 개발
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/controller/CoffeeChatController.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CreateCoffeeChatRoomRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CreateCoffeeChatRoomResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/entity/ChatRoom.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/repository/CoffeeChatRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/service/CoffeeChatService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/CoffeeChatResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CoffeeChatServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/resources/db/migration/V1.3__add_table.sql
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/controller/CoffeeChatControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CoffeeChatRequestDtoTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/service/CoffeeChatServiceTest.java
Labels: Feature, API, Test

#118 [feat] 질문 & 답변 & 로그인 시 정책에 따른 경험치 부여 & 레벨업
  src/main/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerController.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/dto/FindAllAnswerResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/answer/service/AnswerService.java
  src/main/java/com/kernel360/kernelsquare/domain/auth/service/AuthService.java
  src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
  src/main/java/com/kernel360/kernelsquare/domain/member/repository/MemberRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/question/service/QuestionService.java
  src/main/java/com/kernel360/kernelsquare/global/util/experience/ExperienceLogic.java
  src/main/java/com/kernel360/kernelsquare/global/util/experience/ExperiencePolicy.java
  src/main/resources/db/migration/V1.1__add_initial_data.sql
  src/test/java/com/kernel360/kernelsquare/domain/answer/controller/AnswerControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/answer/service/AnswerServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/auth/service/AuthServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
Labels: Feature, Test

#121 [refactor] 예약창 생성 로직 리팩터링
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CreateCoffeeChatRoomRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/entity/ChatRoom.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation/entity/Reservation.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V1.2__add_initial_data.sql
  src/main/resources/db/migration/V1.3__add_table.sql
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/controller/CoffeeChatControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/service/CoffeeChatServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java
Labels: Refactor

#123 Update gradle.yml
  .github/workflows/gradle.yml
Labels: Setting

#124 [fix] 예약창 전체조회, 상세조회 시 해시태그 응답값 버그 수정
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindAllReservationArticleResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindReservationArticleResponse.java
Labels: BugFix

#125 [feat] 예약창 삭제
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/repository/CoffeeChatRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/entity/HashTag.java
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/repository/HashTagRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleController.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/ReservationArticleResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/ReservationArticleServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/test/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java
Labels: Feature, API, Test

#127 Update gradle.yml
  .github/workflows/gradle.yml
Labels: Setting

#128 Update gradle.yml
  .github/workflows/gradle.yml
Labels: Chore

#130 ChatGPT 코드 리뷰 관련 cr.yml 생성
  .github/workflows/cr.yml
Labels: Setting, ChatGPT

#132 Update gradle.yml
  .github/workflows/gradle.yml
Labels: Chore

#122 [feat] 채팅방 입장 기능 개발
  build.gradle
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/controller/CoffeeChatController.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/controller/MessageController.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/controller/ScreenController.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/ChatMessage.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/EnterCoffeeChatRoomRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/EnterCoffeeChatRoomResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/entity/ChatRoom.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/service/CoffeeChatService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/CoffeeChatErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/CoffeeChatResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CoffeeChatServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/main/java/com/kernel360/kernelsquare/global/config/WebSocketConfig.java
  src/main/resources/application.yml
  src/main/resources/templates/chat/screen.html
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/controller/CoffeeChatControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/dto/CoffeeChatRequestDtoTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/service/CoffeeChatServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/socket/StompSocketTest.java
  src/test/java/com/kernel360/kernelsquare/domain/level/service/LevelServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/question/service/QuestionServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java
  src/test/resources/application.yml
Labels: Feature, API, Test, CI

#134 [refactor] 타임리프 관련 코드 수정
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/controller/ScreenController.java
  src/main/resources/templates/chat/screen.html
Labels: Refactor

#139 [bugfix] image_url 컬럼들 varchar(100)에서 varchar(200)으로 변경
  src/main/resources/db/migration/V1.4__alter_table.sql
Labels: BugFix

#141 [feat] 해시태그 조회, 삭제 기능 구현
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/controller/HashtagController.java
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/dto/FindAllHashtagResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/dto/FindHashtagResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/entity/Hashtag.java
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/repository/HashtagRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/service/HashtagService.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindAllReservationArticleResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindReservationArticleResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/entity/ReservationArticle.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/HashTagResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/HashTagServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/test/java/com/kernel360/kernelsquare/domain/hashtag/controller/HashtagControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/hashtag/service/HashtagServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java
Labels: Feature, API, Test, CI

#144 [refactor] 질문 검색 응답 dto 변경
  src/main/java/com/kernel360/kernelsquare/domain/search/controller/SearchController.java
  src/main/java/com/kernel360/kernelsquare/domain/search/dto/SearchQuestionResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/search/service/SearchService.java
  src/test/java/com/kernel360/kernelsquare/domain/search/controller/SearchControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/search/service/SearchServiceTest.java
Labels: Refactor, CI

#147 [bugfix] 회원 이미지 수정시 정상적으로 이미지 URL 처리 로직 추가
  src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java
Labels: BugFix, CI

#155 Update TokenProviderTest.java
  src/test/java/com/kernel360/kernelsquare/global/jwt/TokenProviderTest.java
Labels: BugFix

#152 [feat] 채팅 메시지를 저장하기 위한 몽고 DB 연동
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/controller/MessageController.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/ChatMessage.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/dto/MessageType.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/entity/MongoChatMessage.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/entity/MongoMessageType.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/repository/MongoChatMessageRepository.java
  src/main/java/com/kernel360/kernelsquare/global/compose/mongo/MongoDB.yml
  src/main/resources/application.yml
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/socket/StompSocketTest.java
  src/test/java/com/kernel360/kernelsquare/global/jwt/TokenProviderTest.java
  src/test/resources/application.yml
Labels: Feature, CI

#159 [bugfix] 회원 정보 수정 API 분리
  src/main/java/com/kernel360/kernelsquare/domain/member/controller/MemberController.java
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/FindMemberResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberIntroductionRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/member/dto/UpdateMemberProfileRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/member/entity/Member.java
  src/main/java/com/kernel360/kernelsquare/domain/member/service/MemberService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/MemberResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AnswerServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/AuthorityServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CommonServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/MemberAnswerVoteStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/MemberServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/TokenServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/CorsConfig.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/test/java/com/kernel360/kernelsquare/domain/member/controller/MemberControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/member/service/MemberServiceTest.java
Labels: BugFix, API, Test, Documentation, CI

#161 Update StompSocketTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/socket/StompSocketTest.java
Labels: Test

#162 Update StompSocketTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/socket/StompSocketTest.java
Labels: BugFix, Test

#148 [feat] STOMP와 Kafka 연동
  build.gradle
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/controller/MessageController.java
  src/main/java/com/kernel360/kernelsquare/domain/coffeechat/service/KafkaService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/CoffeeChatErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/CoffeeChatServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/compose/Kafka.yml
  src/main/java/com/kernel360/kernelsquare/global/config/KafkaConsumerConfig.java
  src/main/java/com/kernel360/kernelsquare/global/config/KafkaProducerConfig.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/socket/StompSocketTest.java
Labels: Feature, CI

#165 Update gradle.yml
  .github/workflows/gradle.yml
Labels: BugFix, Chore

#167 Update gradle.yml
  .github/workflows/gradle.yml
Labels: BugFix, Chore

#169 Update StompSocketTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/socket/StompSocketTest.java
Labels: BugFix, Chore

#170 Update StompSocketTest.java
  src/test/java/com/kernel360/kernelsquare/domain/coffeechat/socket/StompSocketTest.java
Labels: BugFix, Chore, CI

#163 [feat] 예약창 조회 리팩터링 & 예약창 수정
  .github/workflows/gradle.yml
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/dto/FindHashtagResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/dto/UpdateHashtagRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/hashtag/repository/HashtagRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation/dto/FindReservationResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation/dto/ReservationDto.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation/dto/UpdateReservationRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation/repository/ReservationRepository.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleController.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/FindReservationArticleResponse.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/dto/UpdateReservationArticleRequest.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/entity/ReservationArticle.java
  src/main/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleService.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/error/code/ReservationArticleErrorCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/response/code/ReservationArticleResponseCode.java
  src/main/java/com/kernel360/kernelsquare/global/common_response/service/code/ReservationArticleServiceStatus.java
  src/main/java/com/kernel360/kernelsquare/global/config/SecurityConfig.java
  src/test/java/com/kernel360/kernelsquare/domain/hashtag/service/HashtagServiceTest.java
  src/test/java/com/kernel360/kernelsquare/domain/reservation_article/controller/ReservationArticleControllerTest.java
  src/test/java/com/kernel360/kernelsquare/domain/reservation_article/service/ReservationArticleServiceTest.java
Labels: Feature, API, Test, Refactor, CI

#172 Update gradle.yml
  .github/workflows/gradle.yml
Labels: BugFix, Chore, CI
