Repository Kernel360/f1-KernelSquare-backend, pull requests merged in 2024-04, with the labels that each got.

#493 [refactor] chatGPT가 답변을 달 때도 질문 작성자에게 알림이 가도록 수정
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/facade/ChatGptFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/service/ChatGptService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/service/ChatGptServiceImpl.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerControllerTest.java
Labels: Refactor

#495 [refactor] 채팅 테스트와 관련된 로직 삭제
  member-api/build.gradle
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaConsumerConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaTopicConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/WebSocketConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/controller/MessageController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/controller/ScreenController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatMessageResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/ChatMessageService.java
  member-api/src/main/resources/application.yml
  member-api/src/main/resources/templates/chatscreen.html
Labels: Refactor

#498 [refactor] 로그인 api 응답 속도 개선
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/auth/command/AuthCommand.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/auth/info/AuthInfo.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/controller/AuthController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/AuthDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/LoginRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/LoginResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/facade/AuthFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/mapper/AuthDtoMapper.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/service/AuthService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/service/TokenProvider.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/validation/AuthValidation.java
  member-api/src/main/resources/application.yml
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/controller/AuthControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/dto/AuthRequestDtoTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/service/AuthServiceTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/service/TokenProviderTest.java
Labels: Refactor

#502 리드미 3차 - nginx 추가
  README.md
Labels: Chore

#501 [refactor] dev 환경이 사라짐에 따른 코드, 설정, ci/cd 수정
  .github/workflows/cd-dev.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/cr.yml
  .gitignore
  core/build.gradle
  core/src/main/java/com/kernelsquare/core/compose/Kafka.yml
  core/src/main/java/com/kernelsquare/core/compose/MongoDB.yml
  core/src/main/java/com/kernelsquare/core/config/JasyptConfig.java
  core/src/main/resources/application.properties
  domain-mongodb/build.gradle
  domain-mongodb/src/main/resources/application.yml
  domain-mongodb/src/test/java/com/kernelsquare/domainmongodb/common/config/TestJasyptConfig.java
  domain-mongodb/src/test/java/com/kernelsquare/domainmongodb/domain/coffeechat/repository/MongoChatMessageRepositoryTest.java
  domain-mongodb/src/test/resources/application.yml
  domain-mysql/src/main/resources/application.yml
  domain-mysql/src/test/resources/application.yml
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java
  member-api/src/main/resources/application-common.yml
  member-api/src/main/resources/application-prod1.yml
  member-api/src/main/resources/application-prod2.yml
  member-api/src/main/resources/application.yml
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/service/TokenProviderTest.java
  member-api/src/test/resources/application.yml
Labels: Setting, Refactor

#503 [merge] develop into main
  .github/workflows/cd-dev.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/cr.yml
  .gitignore
  README.md
  core/build.gradle
  core/src/main/java/com/kernelsquare/core/compose/Kafka.yml
  core/src/main/java/com/kernelsquare/core/compose/MongoDB.yml
  core/src/main/java/com/kernelsquare/core/config/JasyptConfig.java
  core/src/main/resources/application.properties
  domain-mongodb/build.gradle
  domain-mongodb/src/main/resources/application.yml
  domain-mongodb/src/test/java/com/kernelsquare/domainmongodb/common/config/TestJasyptConfig.java
  domain-mongodb/src/test/java/com/kernelsquare/domainmongodb/domain/coffeechat/repository/MongoChatMessageRepositoryTest.java
  domain-mongodb/src/test/resources/application.yml
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerRepository.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerStore.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerStoreImpl.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/auth/command/AuthCommand.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/auth/info/AuthInfo.java
  domain-mysql/src/main/resources/application.yml
  domain-mysql/src/test/resources/application.yml
  member-api/build.gradle
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaConsumerConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaTopicConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/WebSocketConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/controller/AuthController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/AuthDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/LoginRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/LoginResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/facade/AuthFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/mapper/AuthDtoMapper.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/service/AuthService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/service/TokenProvider.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/validation/AuthValidation.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/facade/ChatGptFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/service/ChatGptService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/service/ChatGptServiceImpl.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/controller/MessageController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/controller/ScreenController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatMessageResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/ChatMessageService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/scheduler/manager/SchedulerManagerImpl.java
  member-api/src/main/resources/application-common.yml
  member-api/src/main/resources/application-prod1.yml
  member-api/src/main/resources/application-prod2.yml
  member-api/src/main/resources/application.yml
  member-api/src/main/resources/templates/chatscreen.html
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/controller/AuthControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/dto/AuthRequestDtoTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/service/AuthServiceTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/service/TokenProviderTest.java
  member-api/src/test/resources/application.yml
Labels: Setting, Refactor
