Repository Kernel360/f1-KernelSquare-backend, pull requests merged in 2024-03, with the labels that each got.

#309 fix: 비지니스 정책과 채팅방 이름 길이 제한이 안맞는 부분 수정
  domain-mysql/src/main/resources/db/migration/V2.1__alter_table.sql
Labels: BugFix, QA

#318 [fix] 24시간 미만이 남았더라도 취소는 가능하도록 로직 변경
  core/src/main/java/com/kernelsquare/core/common_response/error/code/ReservationErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/ReservationServiceStatus.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationService.java
Labels: Feature, Refactor, QA

#321 [fix] 커피챗 과거 시간은 예약되지 않도록 검증하는 로직 추가
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/AddReservationMemberRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationServiceTest.java
Labels: Feature, Refactor, QA

#323 [bugfix] 처음 채팅 입장 후 바로 채팅할 수 없는 문제 해결
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaConsumerConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/controller/MessageController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/ChatMessageService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java
Labels: BugFix, QA

#324 [feat] 커널스퀘어 AI 인턴 기능
  README.md
  core/src/main/java/com/kernelsquare/core/common_response/error/code/KernelSquareBotErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/response/code/AnswerResponseCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/AnswerServiceStatus.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/KernelSquareBotServiceStatus.java
  core/src/main/java/com/kernelsquare/core/constants/KernelSquareBotConstants.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerRepository.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/repository/MemberRepository.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/question/info/QuestionInfo.java
  domain-mysql/src/main/resources/application.yml
  domain-mysql/src/main/resources/db/migration/V2.3__add_initial_data.sql
  member-api/build.gradle
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/FeignConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/client/ChatGptClient.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/dto/ChatGptDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/service/ChatGptService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/chatgpt/service/ChatGptServiceImpl.java
  member-api/src/main/resources/application.yml
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerControllerTest.java
Labels: Feature, Setting, API, CI, ChatGPT

#327 [bugfix] rankAnswer 스케줄러에 봇이 단 답변 제외하게끔 로직 수정
  core/src/main/java/com/kernelsquare/core/constants/SystemConstants.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerReaderImpl.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerRepository.java
Labels: BugFix, QA

#329 [bugfix] 질문 목록 조회 시 생성 날짜 기준으로 내림차순 정렬을 하도록 변경
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/question/entity/Question.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/question/controller/QuestionController.java
Labels: BugFix, QA

#328 [feat] 내가 작성한 모각코 리스트 전체 조회
  core/src/main/java/com/kernelsquare/core/common_response/error/code/CodingMeetingErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/CodingMeetingServiceStatus.java
  core/src/main/java/com/kernelsquare/core/constants/SpeLConstants.java
  core/src/main/java/com/kernelsquare/core/type/CodingMeetingReadType.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/entity/CodingMeeting.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/repository/CodingMeetingReader.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/repository/CodingMeetingReaderImpl.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/repository/CodingMeetingRepository.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/service/CodingMeetingService.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/service/CodingMeetingServiceImpl.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting/controller/CodingMeetingController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting/dto/CodingMeetingDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting/service/CodingMeetingFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting_comment/controller/CodingMeetingCommentController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting_comment/dto/CodingMeetingCommentDto.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coding_meeting/controller/CodingMeetingControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coding_meeting_comment/controller/CodingMeetingCommentControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/notice/controller/NoticeControllerTest.java
Labels: Feature, API, Test, CI

#332 [feat] 멘토에게 커피챗 요청하는 기능 개발
  core/src/main/java/com/kernelsquare/core/common_response/error/code/CoffeeChatErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/response/code/CoffeeChatResponseCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/CoffeeChatServiceStatus.java
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/entity/Alert.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/info/AnswerInfo.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coffeechat/command/CoffeeChatCommand.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coffeechat/info/CoffeeChatInfo.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/CoffeeChatRequestAlertMessage.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/mapper/AlertDtoMapper.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/controller/CoffeeChatController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/facade/CoffeeChatFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/mapper/CoffeeChatDtoMapper.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/validation/CoffeeChatValidation.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/CoffeeChatControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/TestMessageController.java
Labels: Feature, API, Test

#335 [feat] 관리자 로그인 기능 개발
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/controller/AuthController.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/CheckDuplicateEmailRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/CheckDuplicateNicknameRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/MemberAdapter.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/MemberAdaptorInstance.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/MemberDetails.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/SignUpRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/SignUpResponse.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/service/AuthService.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/service/MemberDetailService.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/service/TokenProvider.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/validation/AuthValidation.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/auth/controller/AuthControllerTest.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/auth/dto/AuthRequestDtoTest.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/auth/service/AuthServiceTest.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/auth/service/MemberDetailServiceTest.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/repository/MemberReader.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/repository/MemberReaderImpl.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/service/MemberDetailService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/service/MemberDetailServiceTest.java
Labels: Feature, API, Refactor

#338 [refactor] 멘토링 UI / UX 개선 및 버그 픽스로 인한 API 수정
  core/src/main/java/com/kernelsquare/core/validation/validator/BadWordValidator.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/reservation_article/entity/ReservationArticle.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/reservation_article/repository/ReservationArticleRepository.java
  domain-mysql/src/main/resources/db/migration/V2.4__alter_table.sql
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/FindAnswerResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/hashtag/dto/UpdateHashtagRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/UpdateReservationRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/CreateReservationArticleRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/FindAllReservationArticleResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/UpdateReservationArticleRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/controller/ReservationArticleControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/dto/ReservationArticleRequestDtoTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleServiceTest.java
Labels: API, Test, Refactor

#345 [refactor] 관리자 기능 및 회원 기능에 들어갈 공지 기능 수정
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/notice/controller/NoticeController.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/notice/dto/NoticeDto.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/notice/service/NoticeFacade.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/notice/controller/NoticeControllerTest.java
  domain-mysql/src/main/resources/db/migration/V2.5__add_table.sql
  member-api/src/main/java/com/kernelsquare/memberapi/domain/notice/controller/NoticeController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/notice/dto/NoticeDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/notice/service/NoticeFacade.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/notice/controller/NoticeControllerTest.java
Labels: API, Chore

#350 [hotfix] 유저 권한 미체크 해결
  admin-api/src/main/java/com/kernelsquare/adminapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
Labels: BugFix

#351 [merge] develop into main
  admin-api/src/main/java/com/kernelsquare/adminapi/common/config/SecurityConfig.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/notice/controller/NoticeController.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/notice/dto/NoticeDto.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/notice/service/NoticeFacade.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/notice/controller/NoticeControllerTest.java
  domain-mysql/src/main/resources/db/migration/V2.5__add_table.sql
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/notice/controller/NoticeController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/notice/dto/NoticeDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/notice/service/NoticeFacade.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/notice/controller/NoticeControllerTest.java
Labels: BugFix, Refactor

#352 fix: flyway 수정
  domain-mysql/src/main/resources/db/migration/V2.5__add_table.sql
Labels: BugFix

#354 [fix] 플라이웨이 버그 수정
  domain-mysql/src/main/resources/db/migration/V2.5__add_table.sql
Labels: BugFix

#357 [bugfix] 답변 작성자만 수정 삭제 가능하게 수정
  core/src/main/java/com/kernelsquare/core/common_response/error/code/AnswerErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/AnswerServiceStatus.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerReader.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerReaderImpl.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerStore.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerStoreImpl.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/service/AnswerService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/validation/AnswerValidation.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/service/AnswerServiceTest.java
Labels: BugFix, Test, Refactor

#347 [feat] 관리자 회원 관리 기능 개발
  admin-api/build.gradle
  admin-api/src/main/java/com/kernelsquare/adminapi/common/config/SecurityConfig.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/member/controller/MemberController.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/member/dto/FindMemberResponse.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/member/dto/MemberDto.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/member/facade/MemberFacade.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/member/mapper/MemberDtoMapper.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/member/service/MemberService.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/member/controller/MemberControllerTest.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/member/dto/MemberRequestDtoTest.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/member/service/MemberServiceTest.java
  core/src/main/java/com/kernelsquare/core/common_response/error/code/MemberErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/response/code/MemberResponseCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/MemberServiceStatus.java
  core/src/main/java/com/kernelsquare/core/validation/validator/ValueOfEnumValidator.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/authority/repository/AuthorityReader.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/authority/repository/AuthorityReaderImpl.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/command/MemberCommand.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/entity/Member.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/info/MemberInfo.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/repository/MemberStore.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/repository/MemberStoreImpl.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/service/MemberService.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/service/MemberServiceImpl.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_authority/entity/MemberAuthority.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_authority/repository/MemberAuthorityRepository.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_authority/repository/MemberAuthorityStore.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_authority/repository/MemberAuthorityStoreImpl.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/dto/ReservationArticleRequestDtoTest.java
Labels: Feature, API, Test, Refactor

#346 [fix] QA 반영
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/entity/Answer.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/level/entity/Level.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member/entity/Member.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/question/entity/Question.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/rank/entity/Rank.java
  domain-mysql/src/main/resources/db/migration/V2.6__alter_table.sql
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/FindAnswerResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/service/AnswerService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting_comment/dto/CodingMeetingCommentDto.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/controller/AnswerControllerTest.java
Labels: QA

#362 [fix] 모각코 댓글 에러메시지 수정
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting_comment/dto/CodingMeetingCommentDto.java
Labels: BugFix

#360 [setting] Redis, Kafka, MongoDB를 하나의 서버로 분리
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaConsumerConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaProducerConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/RedisConfig.java
  member-api/src/main/resources/application.yml
Labels: Setting, Infra

#364 [infra] 무중단 배포 초기 세팅
  domain-mysql/src/main/resources/application.yml
  member-api/Dockerfile
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/server/ServerController.java
  member-api/src/main/resources/application.yml
Labels: Setting, Deploy, Infra

#366 [setting] ServerController @Value 모듈 명시
  member-api/src/main/java/com/kernelsquare/memberapi/common/server/ServerController.java
Labels: Setting, API, Infra

#367 [setting] develop port 지정
  member-api/src/main/java/com/kernelsquare/memberapi/common/server/ServerController.java
  member-api/src/main/resources/application.yml
Labels: Setting, Infra

#368 [setting] get-server-information 호출 시 값나오게 수정
  member-api/src/main/java/com/kernelsquare/memberapi/common/server/ServerController.java
  member-api/src/main/resources/application.yml
Labels: BugFix, Setting, Infra

#371 setting: 무중단 배포를 위한 cd 워크플로우 추가
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: Setting, Infra

#372 [merge] develop into main
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: Setting, Infra

#373 [setting] 무중단 배포를 위한 cd 워크플로우 수정
  .github/workflows/cd.yml
Labels: Setting, Infra

#374 [merge] develop into main
  .github/workflows/cd.yml
Labels: Setting, Infra

#375 [setting] 무중단 배포를 위한 cd 워크플로우 수정 2차
  .github/workflows/cd.yml
Labels: BugFix, Setting, Infra

#376 [merge] develop into main
  .github/workflows/cd.yml
Labels: BugFix, Setting, Infra

#377 [setting] 무중단 배포를 위한 cd 워크플로우 수정 3차
  .github/workflows/cd.yml
Labels: BugFix, Setting, Infra

#339 [feat] 소셜로그인 기능 구현
  core/src/main/java/com/kernelsquare/core/common_response/error/code/AuthErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/AuthServiceStatus.java
  core/src/main/java/com/kernelsquare/core/type/SocialProvider.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/member_authority/repository/MemberAuthorityRepository.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/social_login/entity/SocialLogin.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/social_login/repository/SocialLoginRepository.java
  member-api/build.gradle
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/OAuth2Config.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/filter/JWTSettingFilter.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/CustomInMemoryOAuth2AuthorizedClientService.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/CustomOAuth2User.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/OAuthAttributes.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginFailureHandler.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/info/OAuth2UserInfo.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/info/OAuth2UserInfoFactory.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/info/impl/GithubOAuth2UserInfo.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/info/impl/GoogleOAuth2UserInfo.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/info/impl/KakaoOAuth2UserInfo.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/info/impl/NaverOAuth2UserInfo.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/service/CustomOAuth2MemberService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/controller/AuthController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/LoginResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/MemberDetails.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/service/AuthService.java
  member-api/src/main/resources/application.yml
Labels: Feature, API, Test

#420 [fix] 깃허브 시크릿 변수 이름 변경
  member-api/src/main/resources/application.yml
Labels: BugFix

#426 [settin] tempo 세팅을 위한 yml 수정
  member-api/src/main/resources/application.yml
Labels: Setting, Infra

#435 [feat] 닉네임 변경 기능 추가
  core/src/main/java/com/kernelsquare/core/common_response/error/code/MemberErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/MemberServiceStatus.java
  member-api/build.gradle
  member-api/src/docs/asciidoc/member-api-index.adoc
  member-api/src/docs/asciidoc/member-nickname-updated.adoc
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/CorsConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/member/controller/MemberController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/member/dto/UpdateMemberNicknameRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/member/service/MemberService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/member/controller/MemberControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/member/service/MemberServiceTest.java
Labels: Feature, API, Test

#433 [refactor] 관리자 인스턴스 서버에 alert-api 서버 모듈 추가함에 따른 Alert 도메인 관련 코드 변경
  .github/workflows/cd.yml
  .gitignore
  build.gradle
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/command/AlertCommand.java
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/entity/Alert.java
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/info/AlertInfo.java
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/repository/AlertReader.java
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/repository/AlertReaderImpl.java
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/repository/AlertRepository.java
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/repository/AlertStore.java
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/repository/AlertStoreImpl.java
  member-api/Dockerfile
  member-api/src/docs/asciidoc/alert-all-found.adoc
  member-api/src/docs/asciidoc/alert-api-index.adoc
  member-api/src/docs/asciidoc/alert-subscribe.adoc
  member-api/src/docs/asciidoc/index.adoc
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaProducerConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaTopicConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/controller/AlertController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/AlertDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/facade/AlertFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/handler/SseEmitterHandler.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/manager/SseManager.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/mapper/AlertDtoMapper.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/service/AlertService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/service/AlertServiceImpl.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/facade/AnswerFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/facade/CoffeeChatFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/scheduler/manager/SchedulerManagerImpl.java
  member-api/src/test/java/com/kernelsquare/memberapi/config/TestWebSocketConfig.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/alert/controller/AlertControllerTest.java
Labels: Feature, Setting, Deploy, API, Test, Refactor

#432 [feature] SEO 최적화를 위한 API (질문 & 모각코 리스트)
  core/src/main/java/com/kernelsquare/core/common_response/response/code/CodingMeetingResponseCode.java
  core/src/main/java/com/kernelsquare/core/common_response/response/code/QuestionResponseCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/CodingMeetingServiceStatus.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/QuestionServiceStatus.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/info/CodingMeetingInfo.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/repository/CodingMeetingReader.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/repository/CodingMeetingReaderImpl.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/service/CodingMeetingService.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/coding_meeting/service/CodingMeetingServiceImpl.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting/controller/CodingMeetingController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting/dto/CodingMeetingDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting/mapper/CodingMeetingDtoMapper.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coding_meeting/service/CodingMeetingFacade.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/question/controller/QuestionController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/question/dto/FindAllQuestionResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/question/dto/FindQuestionIdResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/question/service/QuestionService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coding_meeting/controller/CodingMeetingControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/question/controller/QuestionControllerTest.java
Labels: API, Test, Documentation

#438 [fix] TokenProviderTest redis 연결 하드 코딩으로 임시 방편으로 해결
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/service/TokenProviderTest.java
Labels: BugFix, Test

#439 [setting] develop 브랜치에 merge가 됬을 때 dev 인스턴스 서버에 자동 배포가 되도록 cd-dev 워크플로우 작성
  .github/workflows/cd-dev.yml
  .github/workflows/ci.yml
  domain-mysql/src/test/resources/application.yml
Labels: Setting

#443 [merge] develop into main
  .github/workflows/cd-dev.yml
  .github/workflows/ci.yml
  domain-mysql/src/test/resources/application.yml
  member-api/build.gradle
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/CustomInMemoryOAuth2AuthorizedClientService.java
Labels: BugFix, Setting

#445 [fix] github oauth2 redirect-uri 수정
  member-api/src/main/resources/application.yml
Labels: BugFix

#446 fix: cd-dev 잘못된 부분 수정
  .github/workflows/cd-dev.yml
Labels: BugFix, Setting

#447 fix: cd-dev 잘못된 부분 수정 2차
  .github/workflows/cd-dev.yml
Labels: BugFix, Setting

#448 fix: cd-dev 잘못된 부분 수정 3차
  .github/workflows/cd-dev.yml
Labels: BugFix, Setting

#449 fix: cd-dev 잘못된 부분 수정 4차
  .github/workflows/cd-dev.yml
Labels: BugFix, Setting

#450 fix: 대성님 요청으로 리다이렉트 주소 변경
  member-api/src/main/resources/application.yml
Labels: BugFix

#451 [fix] 소셜로그인 리다이렉트 주소 변경
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginFailureHandler.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java
Labels: BugFix

#452 [fix] 소셜로그인 리다이렉트 주소 변경2
  member-api/src/main/resources/application.yml
Labels: BugFix

#457 [refactor] 채팅 서버에 만료 메시지를 보낼 수 있게 수정
  member-api/src/main/java/com/kernelsquare/memberapi/domain/scheduler/manager/SchedulerManagerImpl.java
  member-api/src/main/resources/templates/chatscreen.html
Labels: Refactor

#459 [fix] cd-dev 버그 수정
  .github/workflows/cd-dev.yml
Labels: BugFix, Setting

#468 [feat] 소셜로그인 메인 반영
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginFailureHandler.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginSuccessHandler.java
  member-api/src/main/resources/application.yml
Labels: Feature, Test, Refactor

#470 [fix] redirectURL 변경
  member-api/src/main/resources/application.yml
Labels: BugFix

#472 [merge] develop into main
  member-api/src/main/resources/application.yml
Labels: BugFix

#480 [fix] 소셜로그인 에러메시지 중첩 문제 해결
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginFailureHandler.java
  member-api/src/main/resources/application.yml
Labels: BugFix

#481 [merge] develop into main
  member-api/src/main/java/com/kernelsquare/memberapi/common/oauth2/handler/OAuth2LoginFailureHandler.java
  member-api/src/main/resources/application.yml
Labels: BugFix

#478 [bugfix] 컨슈머와 프로듀서의 각 위치의 ChatMessageRequest를 인식하기 위한 KafkaProducerConfig 의 JsonSerializer에 ChatMessageRequest 매핑 추가
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaProducerConfig.java
Labels: BugFix

#476 refactor: CoffeeChatService에서 인메모리로 관리하는 chatRoomMemberList 제거
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/EnterCoffeeChatRoomResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/CoffeeChatControllerTest.java
Labels: Refactor

#485 [refactor] 알림 메시지 데이터 구조 변경
  domain-mongodb/build.gradle
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/entity/Alert.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/info/AnswerInfo.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/AlertDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/CoffeeChatRequestAlertMessage.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/QuestionReplyAlertMessage.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/RankAnswerAlertMessage.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/service/AnswerServiceTest.java
Labels: API, Test, Refactor

#486 [merge] develop into main
  domain-mongodb/build.gradle
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/alert/entity/Alert.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/info/AnswerInfo.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaProducerConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/AlertDto.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/CoffeeChatRequestAlertMessage.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/QuestionReplyAlertMessage.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/alert/dto/RankAnswerAlertMessage.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/EnterCoffeeChatRoomResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/service/AnswerServiceTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/CoffeeChatControllerTest.java
Labels: API, Test, Refactor

#490 [Infra] application.yml 에서 management 부분 수정 및 추가
  member-api/src/main/resources/application.yml
Labels: Infra

#488 [refactor] 랭크 스케줄러 수정
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerRepository.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerStore.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/answer/repository/AnswerStoreImpl.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/scheduler/manager/SchedulerManagerImpl.java
Labels: Refactor

#491 [fix] '' 추가
  member-api/src/main/resources/application.yml
Labels: BugFix
