Repository Kernel360/f1-KernelSquare-backend, pull requests merged in 2024-02, with the labels that each got.

#179 [refactor] 각 모듈 application.yml 값 할당하기 위한 수정
  .github/workflows/gradle.yml
Labels: BugFix, Chore

#181 [bugfix] asciidoctor 관련 문제 해결
  admin-api/build.gradle
  member-api/build.gradle
Labels: BugFix, CI

#185 [bugfix] 몽고db 레포지토리 save 안되는 문제 해결
  member-api/src/main/java/com/kernelsquare/memberapi/common/util/ChatMessageConverter.java
  member-api/src/main/resources/application.yml
  member-api/src/main/resources/templates/chat/screen.html
Labels: BugFix, Refactor, CI

#192 Update gradle.yml
  .github/workflows/gradle.yml
Labels: Chore

#193 Update gradle.yml
  .github/workflows/gradle.yml
Labels: BugFix, Chore

#194 Update gradle.yml
  .github/workflows/gradle.yml
Labels: BugFix, Chore, CI

#195 Update gradle.yml
  .github/workflows/gradle.yml
Labels: BugFix, Chore

#187 [bugfix] 멀티모듈 flyway 인식 못하는 문제 해결
  domain-mysql/build.gradle
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/config/FlywayConfig.java
  domain-mysql/src/main/resources/db/migration/V1.0__init_table.sql
  domain-mysql/src/main/resources/db/migration/V1.1__add_initial_data.sql
  domain-mysql/src/main/resources/db/migration/V1.2__add_initial_data.sql
  domain-mysql/src/main/resources/db/migration/V1.3__add_table.sql
  domain-mysql/src/main/resources/db/migration/V1.4__alter_table.sql
  domain-mysql/src/main/resources/db/migration/V1.5__alter_table.sql
  domain-mysql/src/main/resources/migration/V1.5__alter_table.sql
  member-api/src/test/resources/application.yml
  src/main/resources/templates/chat/screen.html
Labels: BugFix, Chore, CI

#207 Update gradle.yml
  .github/workflows/gradle.yml
Labels: BugFix, Chore

#198 [refactor] tech_stack 테이블의 skill 기존 varchar(20)을 50으로 늘림
  domain-mysql/src/main/resources/db/migration/V1.7__alter_table.sql
Labels: Refactor, CI

#210 [feat] 기술 태그 검색 기능 추가
  core/src/main/java/com/kernelsquare/core/common_response/response/code/SearchResponseCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/SearchServiceStatus.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/search/repository/SearchRepository.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/search/repository/SearchRepositoryImpl.java
  domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/search/repository/SearchRepositoryTest.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SecurityConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/search/controller/SearchController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/search/dto/SearchTechStackResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/search/service/SearchService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/search/controller/SearchControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/search/service/SearchServiceTest.java
Labels: Feature, API, CI

#211 [bugfix] chatroom column mismatch 수정
  domain-mysql/src/main/resources/db/migration/V1.8__alter_table.sql
Labels: BugFix, CI

#212 [refactor] 응답으로 보내는 DTO에서 시간과 관련된 멤버 변수에 JsonFormat 어노테이션 달기
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaConsumerConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/KafkaProducerConfig.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/util/ChatMessageConverter.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/FindAnswerResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/controller/MessageController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatMessageRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatMessageResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/FindChatHistoryResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/FindMongoChatMessage.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/KafkaService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/question/dto/FindQuestionResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/FindReservationResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/FindAllReservationArticleResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/FindReservationArticleResponse.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/CoffeeChatControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/TestMessageController.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatServiceTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/socket/StompSocketTest.java
Labels: Refactor, CI

#215 [bugfix] 채팅방 입장 응답에서 expirationTime에 @JsonFormat 추가
  .gitignore
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/EnterCoffeeChatRoomResponse.java
Labels: BugFix, CI, QA

#218 [bug] 예약 게시글 생성 시 시작 시간 들어가지 않던 오류 수정 #217
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/CreateReservationArticleRequest.java
Labels: BugFix, CI, QA

#219 [bugfix] MongoMessageType에서 빠져있는 CODE 추가
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/coffeechat/entity/MongoMessageType.java
Labels: BugFix, CI, QA

#220 [chore] 로그백 설정 추가
  admin-api/src/main/resources/logback.xml
  member-api/src/main/resources/logback.xml
Labels: Chore, CI

#222 [bugfix] 예약창 상세보기에서 멤버 이미지 URL 깨지는 문제 해결
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/FindReservationResponse.java
Labels: BugFix, CI, QA

#224 [hotfix] 회원가입, 로그인, 이메일 중복, 닉네임 중복 체크 시 유효성 검증 순서 및 한글 유효성 검증 추가
  .gitignore
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/controller/AuthController.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/CheckDuplicateEmailRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/CheckDuplicateNicknameRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/LoginRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/SignUpRequest.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/auth/controller/AuthControllerTest.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/auth/dto/AuthRequestDtoTest.java
  core/build.gradle
  core/src/main/java/com/kernelsquare/core/validation/ValidationGroups.java
  core/src/main/java/com/kernelsquare/core/validation/ValidationSequence.java
  core/src/main/java/com/kernelsquare/core/validation/constants/AuthValidationConstants.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/controller/AuthController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/CheckDuplicateEmailRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/CheckDuplicateNicknameRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/LoginRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/SignUpRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/member/dto/UpdateMemberIntroductionRequest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/controller/AuthControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/dto/AuthRequestDtoTest.java
Labels: BugFix, Feature, Refactor, CI

#228 [bugfix] 채팅방 비활성화 스케줄링 동작하게끔 SchedulingConfig 추가
  member-api/src/main/java/com/kernelsquare/memberapi/common/config/SchedulingConfig.java
Labels: BugFix, CI, QA

#229 [bugfix] error레벨 로그에 exception message에 메시지 내용을 넣을 수 있게 수정
  core/src/main/java/com/kernelsquare/core/common_response/error/exception/BusinessException.java
Labels: BugFix, CI, QA

#230 [bugfix] 멘토링 날짜를 신청하기 누른 날짜로 부터 일주일 뒤부터 가능하게끔 수정
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/dto/AddReservationMemberRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationServiceTest.java
Labels: BugFix, CI, QA

#233 [hotfix] 예약 삭제 및 생성 로직 수정
  core/src/main/java/com/kernelsquare/core/common_response/error/code/ReservationErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/ReservationServiceStatus.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/reservation/entity/Reservation.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationServiceTest.java
Labels: Bug, BugFix, CI

#238 [bugfix] 멘토가 만드는 커피챗 생성하기에서 예약 가능 날짜가 넘어서 생성 불가하도록 수정
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java
Labels: BugFix, CI, QA

#256 [bugfix] @AuthenticationPrincipal로 받는 객체에 null이 아닌 제대론 된 값이 들어갈 수 있게 수정
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/MemberAdapter.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/MemberDetails.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/MemberPrincipal.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/service/MemberDetailService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/service/TokenProvider.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationController.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/service/MemberDetailServiceTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/service/ReservationServiceTest.java
Labels: BugFix, API, Test, CI, QA

#264 [chore] 해시태그 테스트 # 삭제
  member-api/src/test/java/com/kernelsquare/memberapi/domain/hashtag/controller/HashtagControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/hashtag/service/HashtagServiceTest.java
Labels: Chore, CI

#266 [bugfix] 본인 질문 글에 답변 불가
  core/src/main/java/com/kernelsquare/core/common_response/error/code/AnswerErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/response/code/AnswerResponseCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/AnswerServiceStatus.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/service/AnswerService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/service/AnswerServiceTest.java
Labels: BugFix, CI, QA

#259 [bugfix] 이미지 검증 로직 추가
  core/src/main/java/com/kernelsquare/core/common_response/ResponseEntityFactory.java
  core/src/main/java/com/kernelsquare/core/common_response/error/GlobalExceptionHandler.java
  core/src/main/java/com/kernelsquare/core/common_response/error/code/ImageErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/ImageServiceStatus.java
  core/src/main/java/com/kernelsquare/core/type/ImageCategory.java
  core/src/main/java/com/kernelsquare/core/type/ImageExtensionType.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/image/service/ImageService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/image/validation/ImageValidation.java
  member-api/src/main/resources/application.yml
Labels: BugFix, Refactor, CI, QA

#262 [bugfix] 예약창 시간 제한 추가 & 예약창 리포지토리 테스트 추가
  core/src/main/java/com/kernelsquare/core/common_response/error/code/ReservationArticleErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/ReservationArticleServiceStatus.java
  domain-mysql/src/main/java/com/kernelsquare/domainmysql/domain/reservation/repository/ReservationRepository.java
  domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/level/repository/LevelRepositoryTest.java
  domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/member_answer_vote/repository/MemberAnswerVoteRepositoryTest.java
  domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/question_tech_stack/repository/QuestionTechStackRepositoryTest.java
  domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/reservation/repository/ReservationRepositoryTest.java
  domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/tech_stack/repository/TechStackRepositoryTest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/member/dto/FindMemberResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleServiceTest.java
Labels: Bug, Test, CI, QA

#267 [bugfix] 예약창 생성 시 예약 일시 체크 로직을 LocalDateTime으로 수정
  domain-mysql/src/test/java/com/kernelsquare/domainmysql/domain/reservation/repository/ReservationRepositoryTest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/service/ReservationArticleServiceTest.java
Labels: Bug, Test, CI, QA

#271 [refactor] 채팅방 상대방 이미지를 보여주기 위한 채팅방 입장하기 관련 로직 리팩토링
  core/src/main/java/com/kernelsquare/core/common_response/error/code/CoffeeChatErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/CoffeeChatServiceStatus.java
  core/src/main/java/com/kernelsquare/core/type/ReservationMemberType.java
  domain-mongodb/src/main/java/com/kernelsquare/domainmongodb/domain/coffeechat/entity/MongoChatMessage.java
  member-api/src/main/java/com/kernelsquare/memberapi/common/util/ChatMessageConverter.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/MemberAdapter.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/MemberAdaptorInstance.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/MemberDetails.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/service/MemberDetailService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/controller/CoffeeChatController.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatMessageRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatMessageResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/ChatRoomMember.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/EnterCoffeeChatRoomRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/dto/EnterCoffeeChatRoomResponse.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatService.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/coffeechat/validation/CoffeeChatValidation.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/controller/CoffeeChatControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/dto/CoffeeChatRequestDtoTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/coffeechat/service/CoffeeChatServiceTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation/controller/ReservationControllerTest.java
Labels: BugFix, API, Test, Refactor, CI, QA

#270 [bugfix] 텍스트 사이즈 Valid 추가 및 테스트 코드
  core/src/main/java/com/kernelsquare/core/common_response/error/code/QuestionErrorCode.java
  core/src/main/java/com/kernelsquare/core/common_response/service/code/QuestionServiceStatus.java
  domain-mysql/src/main/resources/db/migration/V1.9__alter_table.sql
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/CreateAnswerRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/UpdateAnswerRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/member/dto/UpdateMemberIntroductionRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/question/dto/CreateQuestionRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/question/dto/UpdateQuestionRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/CreateReservationArticleRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/reservation_article/dto/UpdateReservationArticleRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/search/service/SearchService.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/dto/AnswerRequestDtoTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/member/dto/MemberRequestDtoTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/question/controller/QuestionControllerTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/question/dto/QuestionRequestDtoTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/reservation_article/dto/ReservationArticleRequestDtoTest.java
Labels: BugFix, Test, CI, QA

#280 [setting] CI 스크립트 target 제거
  .github/workflows/gradle.yml
  README.md
Labels: Setting

#286 [setting] #283 add release
  .github/workflows/echo.yml
  .github/workflows/release_main.yml
  README.md
Labels: Setting, Deploy

#288 [chore] release 테스트
  .github/workflows/echo.yml
  .github/workflows/gradle.yml
  .github/workflows/release_main.yml
  .jpb/jpb-settings.xml
  README.md
Labels: Setting, Deploy, Chore

#290 Setting#283 delete release
  .github/workflows/echo.yml
  .github/workflows/release_main.yml
Labels: Setting

#291 delete release.yml
  .github/workflows/echo.yml
  .github/workflows/release_main.yml
Labels: Setting

#292 [setting] release setting - add yml
  .github/workflows/release.yml
Labels: Setting, Deploy

#293 [setting] add release yml
  .github/workflows/release.yml
Labels: Setting, Deploy

#297 [fix] develop에 안올린 범인을 잡아왔습니다.
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/CheckDuplicateEmailRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/CheckDuplicateNicknameRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/LoginRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/auth/dto/SignUpRequest.java
  admin-api/src/main/java/com/kernelsquare/adminapi/domain/notice/dto/NoticeDto.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/auth/dto/AuthRequestDtoTest.java
  admin-api/src/test/java/com/kernelsquare/adminapi/domain/notice/controller/NoticeControllerTest.java
  core/build.gradle
  core/src/main/java/com/kernelsquare/core/validation/annotations/BadWordFilter.java
  core/src/main/java/com/kernelsquare/core/validation/annotations/EnumValue.java
  core/src/main/java/com/kernelsquare/core/validation/constants/AuthValidationMessage.java
  core/src/main/java/com/kernelsquare/core/validation/constants/BadWordValidationMessage.java
  core/src/main/java/com/kernelsquare/core/validation/validator/BadWordValidator.java
  core/src/main/java/com/kernelsquare/core/validation/validator/ValueOfEnumValidator.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/answer/dto/CreateAnswerRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/CheckDuplicateEmailRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/CheckDuplicateNicknameRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/LoginRequest.java
  member-api/src/main/java/com/kernelsquare/memberapi/domain/auth/dto/SignUpRequest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/answer/dto/AnswerRequestDtoTest.java
  member-api/src/test/java/com/kernelsquare/memberapi/domain/auth/dto/AuthRequestDtoTest.java
Labels: API, CI
